### ISSUE TITLE
Castling impossible with Move::from_str

### ISSUE THREAD

**Issue by lewis-carson** [analog-hors/cozy-chess#4]
Just as title says. `e1g1` returns false when using try_play and does not castle when using try_play_unchecked.

Thanks

**Comment by analog-hors** [comment]
This is intentional. Castling moves are represented with their FRC notation (king takes rook):
> Play a move while checking its legality. Note that this only supports Chess960 style castling.

I may have to make some changes regarding this behaviour. Any thoughts?

**Comment by lewis-carson** [comment]
I'm sorry - looks like I can't read the docs 🙈

I've no thoughts on the matter. It makes sense now that I see how to do it.

Thanks for your help and sorry for wasting your time!
