### ISSUE TITLE
Support UCI castling notation

### ISSUE THREAD

**Issue by cbeust** [analog-hors/cozy-chess#7]
cozy-chess uses the 960 notation for castling, which breaks UCI engines and cutechess.

For example, the position `"r1b1k2r/ppp1n1pp/4p3/3qNp2/3P4/2P3N1/PP2QPPP/R2R2K1 b kq - 1 15"` generates `"e8h8"` as its castling move instead of `"e8g8"`.

It should be possible to configure cozy-chess to generate UCI castling moves.

**Comment by analog-hors** [comment]
I'll consider helper functions to help convert chess960 notation moves to traditional UCI notation and back, but actually changing the internal representation is a lot of work for little benefit, while also introducing additional friction and complexity to the public API.

**Comment by analog-hors** [comment]
Addressed by #9.
